name: "Deploy na main via PR"
on:
  push:
    branches: 
      - main

  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "full"

jobs:
  deploy-master:
    name: "Deploy para produção"
    runs-on: ubuntu-latest
    steps:
      - name: "Pega o código mais recente"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: "SFTP Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "62.72.62.166"
          remote-user: "u305112795"
          remote-port: "65002"
          remote-password: '${{ secrets.FTP_PRODUCTION_PASS }}'
          remote-path: "/home/u305112795/domains/myplaces2go.com.br/public_html"
          ssh-options: "-oHostKeyAlgorithms=+ssh-rsa"
          sync: "full"
