name: "Deploy na main via PR"
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  deploy-master:
    name: "Deploy para produção"
    runs-on: ubuntu-latest
    steps:
      - name: "Pega o código mais recente"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "SFTP Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "82.180.153.145"
          remote-user: "u954404731"
          remote-port: "65002"
          remote-password: '${{ secrets.FTP_PRODUCTION_PASS }}'
          remote-path: "/home/u954404731/domains/myplaces2go.com.br/public_html/backend"
          ssh-options: "-oHostKeyAlgorithms=+ssh-rsa"
          sync: "delta"
